import re

with open('src/app/page.tsx', 'r') as f:
    content = f.read()

texts = """
const TEXTS = {
  esp: {
    sidebarTitle: "Inicio (Escáner)",
    megaGuide: "Mega-Guía Chaguim",
    kosherRecipe: "Recetario Kosher",
    soon: "Pronto",
    hebrewCalendar: "Calendario Hebreo",
    logosCatalog: "Catálogo de Logos",
    insectScanner: "Escáner de Insectos",
    kashrutAlerts: "Alertas de Kashrut",
    kashrutAlertsDesc: "Avisos urgentes sobre productos que perdieron certificación.",
    analyzeProduct: "Analizar Producto",
    photoOrCode: "Fotografía el producto o ingresa su código",
    makeSureLabels: "Asegúrate de que etiquetas sean legibles",
    analyzingAI: "Analizando IA...",
    activateCamera: "Activar Cámara",
    stopCamera: "Detener Cámara",
    capture: "Capturar",
    orAlternatives: "O Alternativas",
    uploadGallery: "Subir desde Galería",
    insertBarcode: "Insertar Código Barras (EAN/UPC)",
    search: "Buscar",
    custom: "Costumbre",
    ashkenazi: "Ashkenazí",
    sephardi: "Sefaradí",
    country: "País",
    mexico: "México",
    usa: "Estados Unidos",
    argentina: "Argentina",
    israel: "Israel",
    spain: "España",
    otherCountry: "Otro País",
    importantNote: "Nota importante:",
    importantNoteDesc1: "Este análisis de inteligencia artificial es una herramienta de asistencia tecnológica de referencia.",
    importantNoteDesc2: "No sustituye de ninguna manera el dictamen ni la revisión de una autoridad rabínica competente.",
    importantNoteDesc3: "En caso de duda sobre la Kashrut de un ingrediente o producto, consulte siempre a su Mashgiach o Rabino experto de confianza.",
    waitingAnalysis: "Esperando Análisis",
    scanProductCamera: "Escanea un producto con la cámara de la izquierda o introduce su código de barras para desglosar el resultado aquí.",
    finalStatus: "Estatus Final",
    aiConfidence: "Certeza IA",
    quickSummary: "Resumen Rápido",
    seal: "Sello",
    none: "Ninguno",
    category: "Categoría",
    openFoodFacts: "Registro OpenFoodFacts",
    product: "Producto",
    unknown: "Desconocido",
    brand: "Marca",
    relevantAlerts: "Alertas Relevantes",
    additionalFilters: "Filtros Adicionales",
    vegan: "Vegano",
    glutenFree: "Sin Gluten",
    dairyFree: "Sin Lácteos",
    dietInfoNA: "Información de dietas no disponible",
    halachicDetail: "Detalle del Análisis Halájico",
    draftingHalachic: "Redactando desglose halájico detallado...",
    noLogicDetails: "No se brindaron detalles adicionales de la lógica.",
    scanAnother: "Escanear Otro Producto",
    recentHistory: "Historial Reciente",
    hide: "Ocultar",
    viewRecipe: "Ver Receta",
    requiredIngredients: "Ingredientes Requeridos",
    noDetailed: "No detallados.",
    prepSteps: "Pasos de Preparación",
    generalInstructions: "Sigue las instrucciones generales de cocina.",
    nextHoliday: "Próxima Festividad",
    daysLeft: "Faltan",
    days: "días",
    preparation: "Preparación",
    pesachPrep1: "Limpieza a fondo y venta de Jametz antes del 12 de Abril.",
    pesachPrep2Ashk: "Kitniyot (arroz, legumbres) no están permitidos.",
    pesachPrep2Sef: "Kitniyot (arroz, frijoles) estricto según la costumbre sefaradí que se siga.",
    pesachPrep3: "Usa la cámara de KosherScan para certificar sellos de \\"Kosher L'Pesach\\".",
    viewFullGuide: "Ver Guía Completa Pesaj"
  },
  eng: {
    sidebarTitle: "Home (Scanner)",
    megaGuide: "Mega-Guide Chaguim",
    kosherRecipe: "Kosher Recipes",
    soon: "Soon",
    hebrewCalendar: "Hebrew Calendar",
    logosCatalog: "Logos Catalog",
    insectScanner: "Insect Scanner",
    kashrutAlerts: "Kashrut Alerts",
    kashrutAlertsDesc: "Urgent notices about products that lost certification.",
    analyzeProduct: "Analyze Product",
    photoOrCode: "Photograph the product or enter its code",
    makeSureLabels: "Make sure labels are readable",
    analyzingAI: "Analyzing AI...",
    activateCamera: "Activate Camera",
    stopCamera: "Stop Camera",
    capture: "Capture",
    orAlternatives: "Or Alternatives",
    uploadGallery: "Upload from Gallery",
    insertBarcode: "Insert Barcode (EAN/UPC)",
    search: "Search",
    custom: "Custom",
    ashkenazi: "Ashkenazi",
    sephardi: "Sephardic",
    country: "Country",
    mexico: "Mexico",
    usa: "United States",
    argentina: "Argentina",
    israel: "Israel",
    spain: "Spain",
    otherCountry: "Other Country",
    importantNote: "Important Note:",
    importantNoteDesc1: "This artificial intelligence analysis is a technological assistance tool for reference.",
    importantNoteDesc2: "It does not substitute the opinion or review of a competent Rabbinic authority in any way.",
    importantNoteDesc3: "When in doubt about the Kashrut of an ingredient or product, always consult your trusted Mashgiach or expert Rabbi.",
    waitingAnalysis: "Waiting for Analysis",
    scanProductCamera: "Scan a product with the camera on the left or enter its barcode to break down the result here.",
    finalStatus: "Final Status",
    aiConfidence: "AI Confidence",
    quickSummary: "Quick Summary",
    seal: "Seal",
    none: "None",
    category: "Category",
    openFoodFacts: "OpenFoodFacts Record",
    product: "Product",
    unknown: "Unknown",
    brand: "Brand",
    relevantAlerts: "Relevant Alerts",
    additionalFilters: "Additional Filters",
    vegan: "Vegan",
    glutenFree: "Gluten Free",
    dairyFree: "Dairy Free",
    dietInfoNA: "Diet information not available",
    halachicDetail: "Halachic Analysis Detail",
    draftingHalachic: "Drafting detailed halachic breakdown...",
    noLogicDetails: "No additional logic details were provided.",
    scanAnother: "Scan Another Product",
    recentHistory: "Recent History",
    hide: "Hide",
    viewRecipe: "View Recipe",
    requiredIngredients: "Required Ingredients",
    noDetailed: "Not detailed.",
    prepSteps: "Preparation Steps",
    generalInstructions: "Follow general cooking instructions.",
    nextHoliday: "Next Holiday",
    daysLeft: "Remaining",
    days: "days",
    preparation: "Preparation",
    pesachPrep1: "Thorough cleaning and sale of Chametz before April 12.",
    pesachPrep2Ashk: "Kitniyot (rice, legumes) are not allowed.",
    pesachPrep2Sef: "Kitniyot (rice, beans) strict according to the Sephardic custom followed.",
    pesachPrep3: "Use the KosherScan camera to certify \\"Kosher L'Pesach\\" seals.",
    viewFullGuide: "View Full Pesach Guide"
  }
};
"""

content = content.replace("import { useState, useRef, useEffect } from 'react';", "import { useState, useRef, useEffect } from 'react';\nimport { useLanguage } from '@/hooks/useLanguage';")
content = content.replace("export default function Home() {", texts + "\nexport default function Home() {\n  const { lang } = useLanguage();\n  const t = TEXTS[lang];")

# Replacements for translation
reps = {
    ">Inicio (Escáner)<": ">{t.sidebarTitle}<",
    ">Mega-Guía Chaguim<": ">{t.megaGuide}<",
    ">Recetario Kosher <": ">{t.kosherRecipe} <",
    ">Pronto<": ">{t.soon}<",
    ">Próximamente<": ">{t.soon}<",
    ">Calendario Hebreo<": ">{t.hebrewCalendar}<",
    ">Catálogo de Logos<": ">{t.logosCatalog}<",
    ">Escáner de Insectos<": ">{t.insectScanner}<",
    ">Alertas de Kashrut<": ">{t.kashrutAlerts}<",
    ">Avisos urgentes sobre productos que perdieron certificación.<": ">{t.kashrutAlertsDesc}<",
    ">Analizar Producto<": ">{t.analyzeProduct}<",
    ">Fotografía el producto o ingresa su código<": ">{t.photoOrCode}<",
    ">Asegúrate de que etiquetas sean legibles<": ">{t.makeSureLabels}<",
    ">Analizando IA...<": ">{t.analyzingAI}<",
    "> Activar Cámara<": "> {t.activateCamera}<",
    "title=\"Detener Cámara\"": "title={t.stopCamera}",
    "> Capturar<": "> {t.capture}<",
    ">O Alternativas<": ">{t.orAlternatives}<",
    "> Subir desde Galería<": "> {t.uploadGallery}<",
    "placeholder=\"Insertar Código Barras (EAN/UPC)\"": "placeholder={t.insertBarcode}",
    ">Buscar<": ">{t.search}<",
    ">Costumbre<": ">{t.custom}<",
    ">Ashkenazí<": ">{t.ashkenazi}<",
    ">Sefaradí<": ">{t.sephardi}<",
    ">País<": ">{t.country}<",
    ">México<": ">{t.mexico}<",
    ">Estados Unidos<": ">{t.usa}<",
    ">Argentina<": ">{t.argentina}<",
    ">Israel<": ">{t.israel}<",
    ">España<": ">{t.spain}<",
    ">Otro País<": ">{t.otherCountry}<",
    ">Nota importante:<": ">{t.importantNote}<",
    "Este análisis de inteligencia artificial es una herramienta de asistencia tecnológica de referencia.": "{t.importantNoteDesc1}",
    "No sustituye de ninguna manera el dictamen ni la revisión de una autoridad rabínica competente.": "{t.importantNoteDesc2}",
    "En caso de duda sobre la Kashrut de un ingrediente o producto, consulte siempre a su Mashgiach o Rabino experto de confianza.": "{t.importantNoteDesc3}",
    ">Esperando Análisis<": ">{t.waitingAnalysis}<",
    "Escanea un producto con la cámara de la izquierda o introduce su código de barras para desglosar el resultado aquí.": "{t.scanProductCamera}",
    ">Estatus Final<": ">{t.finalStatus}<",
    ">Certeza IA<": ">{t.aiConfidence}<",
    "> Resumen Rápido<": "> {t.quickSummary}<",
    ">Sello<": ">{t.seal}<",
    "'Ninguno'": "t.none",
    ">Ninguno<": ">{t.none}<",
    ">Categoría<": ">{t.category}<",
    "> Registro OpenFoodFacts<": "> {t.openFoodFacts}<",
    ">Producto<": ">{t.product}<",
    "'Desconocido'": "t.unknown",
    ">Desconocido<": ">{t.unknown}<",
    ">Marca<": ">{t.brand}<",
    "'N/A'": "'N/A'",
    "> Alertas Relevantes<": "> {t.relevantAlerts}<",
    ">Filtros Adicionales<": ">{t.additionalFilters}<",
    "> Vegano<": "> {t.vegan}<",
    "> Sin Gluten<": "> {t.glutenFree}<",
    "> Sin Lácteos<": "> {t.dairyFree}<",
    ">Información de dietas no disponible<": ">{t.dietInfoNA}<",
    ">Detalle del Análisis Halájico<": ">{t.halachicDetail}<",
    "Redactando desglose halájico detallado...": "{t.draftingHalachic}",
    "'No se brindaron detalles adicionales de la lógica.'": "t.noLogicDetails",
    "Escanear Otro Producto": "{t.scanAnother}",
    "Historial Reciente": "{t.recentHistory}",
    "'Ocultar' : 'Ver Receta'": "isExpanded ? t.hide : t.viewRecipe",
    "Ingredientes Requeridos:": "{t.requiredIngredients}",
    "'No detallados.'": "t.noDetailed",
    "Pasos de Preparación:": "{t.prepSteps}",
    "'Sigue las instrucciones generales de cocina.'": "t.generalInstructions",
    "Próxima Festividad": "{t.nextHoliday}",
    ">Faltan <": ">{t.daysLeft} <",
    "> días<": "> {t.days}<",
    "Preparación (": "{t.preparation} (",
    "Limpieza a fondo y venta de Jametz antes del 12 de Abril.": "{t.pesachPrep1}",
    "'Kitniyot (arroz, legumbres) no están permitidos.' : 'Kitniyot (arroz, frijoles) estricto según la costumbre sefaradí que se siga.'": "userOrigin === 'ashkenazi' ? t.pesachPrep2Ashk : t.pesachPrep2Sef",
    "Usa la cámara de KosherScan para certificar sellos de &quot;Kosher L&apos;Pesach&quot;.": "{t.pesachPrep3}",
    "Ver Guía Completa Pesaj": "{t.viewFullGuide}"
}

for k, v in reps.items():
    content = content.replace(k, v)

# Update subcomponents to receive `t`
content = content.replace("function ResultView({ result, onBack }: { result: any, onBack: () => void }) {", "function ResultView({ result, onBack, t }: { result: any, onBack: () => void, t: any }) {")
content = content.replace("<ResultView result={result} onBack={() => setResult(null)} />", "<ResultView result={result} onBack={() => setResult(null)} t={t} />")

content = content.replace("function ScanHistoryWidget({ history, onRestore }: { history: ScanItem[], onRestore: (data: any) => void }) {", "function ScanHistoryWidget({ history, onRestore, t }: { history: ScanItem[], onRestore: (data: any) => void, t: any }) {")
content = content.replace("<ScanHistoryWidget history={scanHistory} onRestore={(d) => setResult({ ...d, phase: 'detailed' })} />", "<ScanHistoryWidget history={scanHistory} onRestore={(d) => setResult({ ...d, phase: 'detailed' })} t={t} />")

content = content.replace("function RecipeCard({ recipe }: { recipe: any }) {", "function RecipeCard({ recipe, t }: { recipe: any, t: any }) {")
content = content.replace("<RecipeCard recipe={result.receta_sugerida} />", "<RecipeCard recipe={result.receta_sugerida} t={t} />")

content = content.replace("function ChaguimWidget({ userOrigin }: { userOrigin: string }) {", "function ChaguimWidget({ userOrigin, t }: { userOrigin: string, t: any }) {")
content = content.replace("<ChaguimWidget userOrigin={userOrigin} />", "<ChaguimWidget userOrigin={userOrigin} t={t} />")

with open('src/app/page.tsx', 'w') as f:
    f.write(content)

print("Replacement done!")
